name: Build and deploy ASP.Net Core app to Azure Web App - chessmaster-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Set up .NET Core SDK
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Restore dependencies for the project
      - name: Restore dependencies
        run: dotnet restore ChessMasterAPI/ChessMasterAPI.csproj  # Restore for the correct project

      # Build the project
      - name: Build with dotnet
        run: dotnet build ChessMasterAPI/ChessMasterAPI.csproj --configuration Release  # Ensure it builds correctly

      # Debugging step to list files in ChessMasterAPI directory
      - name: List Files for Debugging
        run: ls -R ChessMasterAPI/

      # Publish the project for deployment
      - name: Publish project
        run: dotnet publish ChessMasterAPI/ChessMasterAPI.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp  # Publish the app

      # Upload build artifact for the deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download the artifact from the build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      # Deploy the artifact to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'chessmaster-api'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      # Install dotnet-ef globally (required for migrations)
      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef

      # Rebuild the project before migrations (to ensure obj is available)
      - name: Rebuild project
        run: dotnet build ChessMasterAPI/ChessMasterAPI.csproj --configuration Release

      # Run the Entity Framework Core migrations
      - name: Run Entity Framework Migrations
        run: dotnet ef database update --connection "${{ secrets.AZURE_POSTGRES_CONNECTION_STRING }}" --project ChessMasterAPI/ChessMasterAPI.csproj
